### ISSUE TITLE
Allow dynamically setting the site

### ISSUE THREAD

**Issue by AndyWendt** [SocialiteProviders/StackExchange#2]
It would be nice to have a way to set the specific StackExchange site dynamically.  Currently, it is set through the `services` array.

**Comment by AndyWendt** [comment]
could use the new config option in the manager class

**Comment by DraperStudio** [comment]
How would that look like with the config option? Haven't looked at it yet.

**Comment by DraperStudio** [comment]
https://github.com/SocialiteProviders/Manager/pull/24

**Comment by AndyWendt** [comment]
Merged that into master and pushed out a new version

**Comment by AndyWendt** [comment]
I think dynamically overriding the config for a specific endpoint is what I was talking about: https://github.com/SocialiteProviders/Manager#dynamically-passing-a-config

But I need to ponder this about what may be the best way to go about this.

**Comment by DraperStudio** [comment]
Maybe we should introduce our own `Socialite` Facade and Class which would extend the base Socialite stuff but we could do a bit more stuff while still maintaining all Socialite functionality.

The Config like it is a the moment seems a bit nasty to me because you need to put in the key, secret, etc. manually.

I would rather see something in this direction.

```php
Route::group(['middleware' => ['web']], function () {
    \Route::get('/', function() {
        return SocialProvider::driver('stackexchange')->config([
            'key' => 'yourkeyfortheservice', 'site' => 'stackoverflow'
        ])->redirect();
    });

    \Route::get('/callback', function () {
        $user = \SocialProvider::driver('stackexchange')->user();

        dd($user);
    });
});
```

We should store the `config`-value then somewhre in a container so that `\SocialProvider::driver('stackexchange')->user();` doesn't need to be changed and still knows the config if required.

**Comment by AndyWendt** [comment]
I think you are right about creating our own facade.  That will allow us to have a lot more control over the situation.

**Comment by DraperStudio** [comment]
I will play around with a few things in the next days to figure out which is the best way for a simple and clean interface which requires as less extra user-side work as possible.
